#!/usr/bin/python3

import fileinput

words = []

# word processing
for line in fileinput.input():
    words_to_add = line.rstrip().split(" ")
    for word in words_to_add:
        if len(word) == 0:
            continue
        if all([letter.isalpha() for letter in word]):
            words.append(word.lower())

# summing up the counts for each word
count = 0
for word in words:
    count += max([word.count(letter) for letter in word])

print(count)

# SOURCES
# https://stackoverflow.com/questions/22520932/python-remove-all-non-alphabet-chars-from-string
# https://www.geeksforgeeks.org/python-boolean-list-and-and-or-operations/
# https://stackoverflow.com/questions/1155617/count-the-number-occurrences-of-a-character-in-a-string
